
/* SPDX-License-Identifier: (LGPL-2.1 OR BSD-2-Clause) */

/* THIS FILE IS AUTOGENERATED BY BPFTOOL! */
#ifndef __REGISTER_VM_BPF_SKEL_H__
#define __REGISTER_VM_BPF_SKEL_H__

#include <errno.h>
#include <stdlib.h>
#include <bpf/libbpf.h>

#define BPF_SKEL_SUPPORTS_MAP_AUTO_ATTACH 1

struct register_vm_bpf {
	struct bpf_object_skeleton *skeleton;
	struct bpf_object *obj;
	struct {
		struct bpf_map *vms;
		struct bpf_map *vcpus;
	} maps;

#ifdef __cplusplus
	static inline struct register_vm_bpf *open(const struct bpf_object_open_opts *opts = nullptr);
	static inline struct register_vm_bpf *open_and_load();
	static inline int load(struct register_vm_bpf *skel);
	static inline int attach(struct register_vm_bpf *skel);
	static inline void detach(struct register_vm_bpf *skel);
	static inline void destroy(struct register_vm_bpf *skel);
	static inline const void *elf_bytes(size_t *sz);
#endif /* __cplusplus */
};

static void
register_vm_bpf__destroy(struct register_vm_bpf *obj)
{
	if (!obj)
		return;
	if (obj->skeleton)
		bpf_object__destroy_skeleton(obj->skeleton);
	free(obj);
}

static inline int
register_vm_bpf__create_skeleton(struct register_vm_bpf *obj);

static inline struct register_vm_bpf *
register_vm_bpf__open_opts(const struct bpf_object_open_opts *opts)
{
	struct register_vm_bpf *obj;
	int err;

	obj = (struct register_vm_bpf *)calloc(1, sizeof(*obj));
	if (!obj) {
		errno = ENOMEM;
		return NULL;
	}

	err = register_vm_bpf__create_skeleton(obj);
	if (err)
		goto err_out;

	err = bpf_object__open_skeleton(obj->skeleton, opts);
	if (err)
		goto err_out;

	return obj;
err_out:
	register_vm_bpf__destroy(obj);
	errno = -err;
	return NULL;
}

static inline struct register_vm_bpf *
register_vm_bpf__open(void)
{
	return register_vm_bpf__open_opts(NULL);
}

static inline int
register_vm_bpf__load(struct register_vm_bpf *obj)
{
	return bpf_object__load_skeleton(obj->skeleton);
}

static inline struct register_vm_bpf *
register_vm_bpf__open_and_load(void)
{
	struct register_vm_bpf *obj;
	int err;

	obj = register_vm_bpf__open();
	if (!obj)
		return NULL;
	err = register_vm_bpf__load(obj);
	if (err) {
		register_vm_bpf__destroy(obj);
		errno = -err;
		return NULL;
	}
	return obj;
}

static inline int
register_vm_bpf__attach(struct register_vm_bpf *obj)
{
	return bpf_object__attach_skeleton(obj->skeleton);
}

static inline void
register_vm_bpf__detach(struct register_vm_bpf *obj)
{
	bpf_object__detach_skeleton(obj->skeleton);
}

static inline const void *register_vm_bpf__elf_bytes(size_t *sz);

static inline int
register_vm_bpf__create_skeleton(struct register_vm_bpf *obj)
{
	struct bpf_object_skeleton *s;
	struct bpf_map_skeleton *map __attribute__((unused));
	int err;

	s = (struct bpf_object_skeleton *)calloc(1, sizeof(*s));
	if (!s)	{
		err = -ENOMEM;
		goto err;
	}

	s->sz = sizeof(*s);
	s->name = "register_vm_bpf";
	s->obj = &obj->obj;

	/* maps */
	s->map_cnt = 2;
	s->map_skel_sz = 24;
	s->maps = (struct bpf_map_skeleton *)calloc(s->map_cnt,
			sizeof(*s->maps) > 24 ? sizeof(*s->maps) : 24);
	if (!s->maps) {
		err = -ENOMEM;
		goto err;
	}

	map = (struct bpf_map_skeleton *)((char *)s->maps + 0 * s->map_skel_sz);
	map->name = "vms";
	map->map = &obj->maps.vms;

	map = (struct bpf_map_skeleton *)((char *)s->maps + 1 * s->map_skel_sz);
	map->name = "vcpus";
	map->map = &obj->maps.vcpus;

	s->data = register_vm_bpf__elf_bytes(&s->data_sz);

	obj->skeleton = s;
	return 0;
err:
	bpf_object__destroy_skeleton(s);
	return err;
}

static inline const void *register_vm_bpf__elf_bytes(size_t *sz)
{
	static const char data[] __attribute__((__aligned__(8))) = "\
\x7f\x45\x4c\x46\x02\x01\x01\0\0\0\0\0\0\0\0\0\x01\0\xf7\0\x01\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\x20\x0c\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\x40\0\x14\0\
\x01\0\x47\x50\x4c\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x01\x11\x01\x25\x25\x13\x05\x03\x25\x72\x17\x10\x17\x1b\x25\x73\x17\0\0\x02\
\x34\0\x03\x25\x49\x13\x3f\x19\x3a\x0b\x3b\x0b\x02\x18\0\0\x03\x01\x01\x49\x13\
\0\0\x04\x21\0\x49\x13\x37\x0b\0\0\x05\x24\0\x03\x25\x3e\x0b\x0b\x0b\0\0\x06\
\x24\0\x03\x25\x0b\x0b\x3e\x0b\0\0\x07\x13\x01\x0b\x0b\x3a\x0b\x3b\x0b\0\0\x08\
\x0d\0\x03\x25\x49\x13\x3a\x0b\x3b\x0b\x38\x0b\0\0\x09\x0f\0\x49\x13\0\0\x0a\
\x21\0\x49\x13\x37\x06\0\0\x0b\x13\x01\x03\x25\x0b\x0b\x3a\x0b\x3b\x0b\0\0\x0c\
\x16\0\x49\x13\x03\x25\x3a\x0b\x3b\x05\0\0\0\x40\x01\0\0\x05\0\x01\x08\0\0\0\0\
\x01\0\x0c\0\x01\x08\0\0\0\0\0\0\0\x02\x08\0\0\0\x02\x03\x29\0\0\0\0\x07\x02\
\xa1\0\x03\x35\0\0\0\x04\x39\0\0\0\x04\0\x05\x04\x06\x01\x06\x05\x08\x07\x02\
\x06\x48\0\0\0\0\x11\x02\xa1\x01\x07\x20\0\x0c\x08\x07\x71\0\0\0\0\x0d\0\x08\
\x09\x86\0\0\0\0\x0e\x08\x08\x0a\x9a\0\0\0\0\x0f\x10\x08\x0b\xab\0\0\0\0\x10\
\x18\0\x09\x76\0\0\0\x03\x82\0\0\0\x04\x39\0\0\0\x01\0\x05\x08\x05\x04\x09\x8b\
\0\0\0\x03\x82\0\0\0\x0a\x39\0\0\0\x80\x96\x98\0\0\x09\x9f\0\0\0\x03\x35\0\0\0\
\x04\x39\0\0\0\x40\0\x09\xb0\0\0\0\x0b\x10\x84\x01\x06\x08\x0c\xc8\0\0\0\x01\
\x07\0\x08\x0d\xd4\0\0\0\x01\x08\x80\0\x03\x35\0\0\0\x04\x39\0\0\0\x80\0\x0c\
\xdd\0\0\0\x0f\x02\x03\x5e\x05\x0e\x07\x04\x02\x11\xec\0\0\0\0\x18\x02\xa1\x02\
\x07\x20\0\x13\x08\x07\x71\0\0\0\0\x14\0\x08\x09\x86\0\0\0\0\x15\x08\x08\x0a\
\x15\x01\0\0\0\x16\x10\x08\x0b\x1a\x01\0\0\0\x17\x18\0\x09\xd4\0\0\0\x09\x1f\
\x01\0\0\x0b\x14\x40\x01\x0b\x08\x12\xd4\0\0\0\x01\x0c\0\x08\x13\x37\x01\0\0\
\x01\x0d\x04\0\x03\x35\0\0\0\x04\x39\0\0\0\x3c\0\0\x58\0\0\0\x05\0\0\0\0\0\0\0\
\x27\0\0\0\x4a\0\0\0\x8b\0\0\0\x93\0\0\0\x98\0\0\0\xac\0\0\0\xb0\0\0\0\xb5\0\0\
\0\xb9\0\0\0\xc5\0\0\0\xc9\0\0\0\xcf\0\0\0\xda\0\0\0\xe8\0\0\0\xf5\0\0\0\xfb\0\
\0\0\0\x01\0\0\x06\x01\0\0\x11\x01\0\0\x19\x01\0\0\x55\x62\x75\x6e\x74\x75\x20\
\x63\x6c\x61\x6e\x67\x20\x76\x65\x72\x73\x69\x6f\x6e\x20\x31\x34\x2e\x30\x2e\
\x30\x2d\x31\x75\x62\x75\x6e\x74\x75\x31\x2e\x31\0\x65\x62\x70\x66\x2f\x72\x65\
\x67\x69\x73\x74\x65\x72\x5f\x76\x6d\x2f\x72\x65\x67\x69\x73\x74\x65\x72\x5f\
\x76\x6d\x2e\x62\x70\x66\x2e\x63\0\x2f\x68\x6f\x6d\x65\x2f\x66\x75\x72\x65\x68\
\x5f\x6d\x69\x74\x6f\x74\x6f\x2f\x50\x68\x61\x6e\x74\x6f\x6d\x5f\x54\x72\x61\
\x63\x6b\x65\x72\x2f\x70\x68\x61\x6e\x74\x6f\x6d\x2d\x74\x72\x61\x63\x6b\x65\
\x72\x2f\x70\x76\x73\x68\x63\x68\x65\x64\x2d\x68\x6f\x73\x74\0\x4c\x49\x43\x45\
\x4e\x53\x45\0\x63\x68\x61\x72\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\x53\x49\x5a\
\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x76\x6d\x73\0\x74\x79\x70\x65\0\x69\x6e\x74\
\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\x65\x73\0\x6b\x65\x79\0\x76\x61\x6c\x75\
\x65\0\x71\x6d\x70\x5f\x73\x6f\x63\x6b\x65\x74\0\x70\x68\x61\x6e\x74\x6f\x6d\
\x5f\x63\x6f\x75\x6e\x74\0\x75\x6e\x73\x69\x67\x6e\x65\x64\x20\x69\x6e\x74\0\
\x5f\x5f\x75\x33\x32\0\x76\x6d\x5f\x74\0\x76\x63\x70\x75\x73\0\x76\x63\x70\x75\
\x5f\x69\x6e\x64\x65\x78\0\x76\x6d\x5f\x6e\x61\x6d\x65\0\x76\x63\x70\x75\x5f\
\x74\0\x1c\0\0\0\x05\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\x9f\xeb\x01\0\x18\0\0\0\0\0\0\0\x50\x02\0\0\x50\x02\0\0\xa4\0\0\0\0\0\0\0\0\0\
\0\x02\x03\0\0\0\x01\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\x01\0\0\0\0\0\0\0\x03\0\
\0\0\0\x02\0\0\0\x04\0\0\0\x01\0\0\0\x05\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\
\0\0\0\0\0\0\x02\x06\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x02\0\0\0\x04\0\0\0\x80\
\x96\x98\0\0\0\0\0\0\0\0\x02\x09\0\0\0\x19\0\0\0\0\0\0\x01\x01\0\0\0\x08\0\0\
\x01\0\0\0\0\0\0\0\x03\0\0\0\0\x08\0\0\0\x04\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\x02\
\x0b\0\0\0\x1e\0\0\0\x02\0\0\x04\x84\0\0\0\x23\0\0\0\x0c\0\0\0\0\0\0\0\x2e\0\0\
\0\x0d\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x08\0\0\0\x04\0\0\0\x80\0\0\0\
\x3c\0\0\0\0\0\0\x08\x0e\0\0\0\x42\0\0\0\0\0\0\x01\x04\0\0\0\x20\0\0\0\0\0\0\0\
\x04\0\0\x04\x20\0\0\0\x4f\0\0\0\x01\0\0\0\0\0\0\0\x54\0\0\0\x05\0\0\0\x40\0\0\
\0\x60\0\0\0\x07\0\0\0\x80\0\0\0\x64\0\0\0\x0a\0\0\0\xc0\0\0\0\x6a\0\0\0\0\0\0\
\x0e\x0f\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x02\x0d\0\0\0\0\0\0\0\0\0\0\x02\x13\0\0\
\0\x6e\0\0\0\x02\0\0\x04\x40\0\0\0\x75\0\0\0\x0d\0\0\0\0\0\0\0\x80\0\0\0\x14\0\
\0\0\x20\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x08\0\0\0\x04\0\0\0\x3c\0\0\0\0\0\0\0\
\x04\0\0\x04\x20\0\0\0\x4f\0\0\0\x01\0\0\0\0\0\0\0\x54\0\0\0\x05\0\0\0\x40\0\0\
\0\x60\0\0\0\x11\0\0\0\x80\0\0\0\x64\0\0\0\x12\0\0\0\xc0\0\0\0\x88\0\0\0\0\0\0\
\x0e\x15\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\x03\0\0\0\0\x08\0\0\0\x04\0\0\0\x04\0\0\
\0\x8e\0\0\0\0\0\0\x0e\x17\0\0\0\x01\0\0\0\x96\0\0\0\x02\0\0\x0f\0\0\0\0\x10\0\
\0\0\0\0\0\0\x20\0\0\0\x16\0\0\0\0\0\0\0\x20\0\0\0\x9c\0\0\0\x01\0\0\x0f\0\0\0\
\0\x18\0\0\0\0\0\0\0\x04\0\0\0\0\x69\x6e\x74\0\x5f\x5f\x41\x52\x52\x41\x59\x5f\
\x53\x49\x5a\x45\x5f\x54\x59\x50\x45\x5f\x5f\0\x63\x68\x61\x72\0\x76\x6d\x5f\
\x74\0\x71\x6d\x70\x5f\x73\x6f\x63\x6b\x65\x74\0\x70\x68\x61\x6e\x74\x6f\x6d\
\x5f\x63\x6f\x75\x6e\x74\0\x5f\x5f\x75\x33\x32\0\x75\x6e\x73\x69\x67\x6e\x65\
\x64\x20\x69\x6e\x74\0\x74\x79\x70\x65\0\x6d\x61\x78\x5f\x65\x6e\x74\x72\x69\
\x65\x73\0\x6b\x65\x79\0\x76\x61\x6c\x75\x65\0\x76\x6d\x73\0\x76\x63\x70\x75\
\x5f\x74\0\x76\x63\x70\x75\x5f\x69\x6e\x64\x65\x78\0\x76\x6d\x5f\x6e\x61\x6d\
\x65\0\x76\x63\x70\x75\x73\0\x4c\x49\x43\x45\x4e\x53\x45\0\x2e\x6d\x61\x70\x73\
\0\x6c\x69\x63\x65\x6e\x73\x65\0\x6d\0\0\0\x05\0\x08\0\x65\0\0\0\x08\x01\x01\
\xfb\x0e\x0d\0\x01\x01\x01\x01\0\0\0\x01\0\0\x01\x01\x01\x1f\x02\0\0\0\0\x41\0\
\0\0\x03\x01\x1f\x02\x0f\x05\x1e\x03\x49\0\0\0\0\xf2\x1a\xb7\x7c\xfb\xd5\xc4\
\x6a\x8f\x99\x45\x73\x2a\xbd\x87\xc3\x6c\0\0\0\x01\xa2\x86\x1b\xb4\x20\x61\x96\
\x39\xcc\x5c\x1f\x9b\x32\x4c\x3a\xab\x7e\0\0\0\x01\x06\x9e\x89\x72\x83\xe2\x39\
\x31\x0b\xc7\x04\xcf\xae\x08\x2b\xee\x2f\x68\x6f\x6d\x65\x2f\x66\x75\x72\x65\
\x68\x5f\x6d\x69\x74\x6f\x74\x6f\x2f\x50\x68\x61\x6e\x74\x6f\x6d\x5f\x54\x72\
\x61\x63\x6b\x65\x72\x2f\x70\x68\x61\x6e\x74\x6f\x6d\x2d\x74\x72\x61\x63\x6b\
\x65\x72\x2f\x70\x76\x73\x68\x63\x68\x65\x64\x2d\x68\x6f\x73\x74\0\x69\x6e\x63\
\x6c\x75\x64\x65\0\x65\x62\x70\x66\x2f\x72\x65\x67\x69\x73\x74\x65\x72\x5f\x76\
\x6d\x2f\x72\x65\x67\x69\x73\x74\x65\x72\x5f\x76\x6d\x2e\x62\x70\x66\x2e\x63\0\
\x72\x65\x67\x69\x73\x74\x65\x72\x5f\x76\x6d\x5f\x62\x70\x66\x2e\x68\0\x76\x6d\
\x6c\x69\x6e\x75\x78\x2e\x68\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x9d\0\0\0\x04\0\xf1\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x05\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x08\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x0a\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\
\x0b\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x03\0\x0f\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\x03\0\x11\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\0\0\0\x11\
\0\x03\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\x38\0\0\0\x11\0\x04\0\0\0\0\0\0\0\0\
\0\x20\0\0\0\0\0\0\0\x15\0\0\0\x11\0\x04\0\x20\0\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\
\x08\0\0\0\0\0\0\0\x03\0\0\0\x02\0\0\0\x11\0\0\0\0\0\0\0\x03\0\0\0\x03\0\0\0\
\x15\0\0\0\0\0\0\0\x03\0\0\0\x06\0\0\0\x1a\0\0\0\0\0\0\0\x03\0\0\0\x05\0\0\0\
\x08\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x0c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x10\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x14\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x18\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x1c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x20\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x24\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x28\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x2c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x30\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x34\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x38\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x3c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x40\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x44\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x48\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x4c\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x50\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x54\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\
\x58\0\0\0\0\0\0\0\x03\0\0\0\x04\0\0\0\x08\0\0\0\0\0\0\0\x02\0\0\0\x08\0\0\0\
\x10\0\0\0\0\0\0\0\x02\0\0\0\x09\0\0\0\x18\0\0\0\0\0\0\0\x02\0\0\0\x0a\0\0\0\
\x3c\x02\0\0\0\0\0\0\x04\0\0\0\x09\0\0\0\x48\x02\0\0\0\0\0\0\x04\0\0\0\x0a\0\0\
\0\x60\x02\0\0\0\0\0\0\x04\0\0\0\x08\0\0\0\x22\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\
\0\x26\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\x32\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\
\x47\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\x5c\0\0\0\0\0\0\0\x03\0\0\0\x07\0\0\0\
\x08\x09\x0a\0\x2e\x64\x65\x62\x75\x67\x5f\x61\x62\x62\x72\x65\x76\0\x2e\x74\
\x65\x78\x74\0\x76\x63\x70\x75\x73\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\
\x5f\x73\x74\x72\x5f\x6f\x66\x66\x73\x65\x74\x73\0\x2e\x6d\x61\x70\x73\0\x76\
\x6d\x73\0\x2e\x64\x65\x62\x75\x67\x5f\x73\x74\x72\0\x2e\x64\x65\x62\x75\x67\
\x5f\x6c\x69\x6e\x65\x5f\x73\x74\x72\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\
\x5f\x61\x64\x64\x72\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x69\x6e\x66\
\x6f\0\x2e\x6c\x6c\x76\x6d\x5f\x61\x64\x64\x72\x73\x69\x67\0\x6c\x69\x63\x65\
\x6e\x73\x65\0\x2e\x72\x65\x6c\x2e\x64\x65\x62\x75\x67\x5f\x6c\x69\x6e\x65\0\
\x72\x65\x67\x69\x73\x74\x65\x72\x5f\x76\x6d\x2e\x62\x70\x66\x2e\x63\0\x2e\x73\
\x74\x72\x74\x61\x62\0\x2e\x73\x79\x6d\x74\x61\x62\0\x2e\x72\x65\x6c\x2e\x42\
\x54\x46\0\x4c\x49\x43\x45\x4e\x53\x45\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\xaf\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x4b\
\x0b\0\0\0\0\0\0\xd0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x0f\0\0\0\x01\0\0\0\x06\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x85\0\0\0\
\x01\0\0\0\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x32\0\0\0\x01\0\0\0\x03\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\0\0\0\0\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x08\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x88\0\0\0\0\0\0\0\x8f\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\0\x6b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x17\x01\
\0\0\0\0\0\0\x44\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\x67\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x08\x09\0\0\0\0\0\0\
\x40\0\0\0\0\0\0\0\x13\0\0\0\x06\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x1f\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x5b\x02\0\0\0\0\0\0\x5c\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1b\0\0\0\x09\0\0\0\
\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x48\x09\0\0\0\0\0\0\x50\x01\0\0\0\0\0\0\x13\
\0\0\0\x08\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x3c\0\0\0\x01\0\0\0\x30\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\x02\0\0\0\0\0\0\x20\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x5b\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\0\0\0\xd7\x03\0\0\0\0\0\0\x20\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x57\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x98\x0a\0\0\0\0\0\0\x30\0\0\0\0\0\0\0\x13\0\0\0\x0b\0\0\0\x08\0\0\0\0\0\0\0\
\x10\0\0\0\0\0\0\0\xc3\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf8\x03\
\0\0\0\0\0\0\x0c\x03\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\xbf\0\0\0\x09\0\0\0\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xc8\x0a\0\0\0\0\0\0\
\x30\0\0\0\0\0\0\0\x13\0\0\0\x0d\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x91\
\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x04\x07\0\0\0\0\0\0\x71\0\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x8d\0\0\0\x09\0\0\0\
\x40\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xf8\x0a\0\0\0\0\0\0\x50\0\0\0\0\0\0\0\x13\0\
\0\0\x0f\0\0\0\x08\0\0\0\0\0\0\0\x10\0\0\0\0\0\0\0\x47\0\0\0\x01\0\0\0\x30\0\0\
\0\0\0\0\0\0\0\0\0\0\0\0\0\x75\x07\0\0\0\0\0\0\x88\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\x01\0\0\0\0\0\0\0\x01\0\0\0\0\0\0\0\x77\0\0\0\x03\x4c\xff\x6f\0\0\0\x80\0\0\
\0\0\0\0\0\0\0\0\0\0\x48\x0b\0\0\0\0\0\0\x03\0\0\0\0\0\0\0\x13\0\0\0\0\0\0\0\
\x01\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\xb7\0\0\0\x02\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\
\0\0\0\0\0\x08\0\0\0\0\0\0\x08\x01\0\0\0\0\0\0\x01\0\0\0\x08\0\0\0\x08\0\0\0\0\
\0\0\0\x18\0\0\0\0\0\0\0";

	*sz = sizeof(data) - 1;
	return (const void *)data;
}

#ifdef __cplusplus
struct register_vm_bpf *register_vm_bpf::open(const struct bpf_object_open_opts *opts) { return register_vm_bpf__open_opts(opts); }
struct register_vm_bpf *register_vm_bpf::open_and_load() { return register_vm_bpf__open_and_load(); }
int register_vm_bpf::load(struct register_vm_bpf *skel) { return register_vm_bpf__load(skel); }
int register_vm_bpf::attach(struct register_vm_bpf *skel) { return register_vm_bpf__attach(skel); }
void register_vm_bpf::detach(struct register_vm_bpf *skel) { register_vm_bpf__detach(skel); }
void register_vm_bpf::destroy(struct register_vm_bpf *skel) { register_vm_bpf__destroy(skel); }
const void *register_vm_bpf::elf_bytes(size_t *sz) { return register_vm_bpf__elf_bytes(sz); }
#endif /* __cplusplus */

__attribute__((unused)) static void
register_vm_bpf__assert(struct register_vm_bpf *s __attribute__((unused)))
{
#ifdef __cplusplus
#define _Static_assert static_assert
#endif
#ifdef __cplusplus
#undef _Static_assert
#endif
}

#endif /* __REGISTER_VM_BPF_SKEL_H__ */
